- name: configure logmatic on node
  hosts: localhost
  remote_user: root
  become: yes
  vars:
    AWS_REGION: us-east-1
    NUXEO_ROLE_PATH: "roles/nuxeo"
    APP_DIR: "/apps"
    SERVICE: app
  tasks:
   - include: roles/nuxeo/tasks/nuxeo-json2hcl-install.yml
   - include: roles/nuxeo/tasks/nuxeo-syslogng-configure.yml